[package]
description = "A simple art program"
edition = "2023"
license = "AGPL"
name = "art"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
